version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Specify your desired Node.js version
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the application..."
      # If you have a build step (e.g., transpiling, bundling), include it here
      # - npm run build 
  post_build:
    commands:
      - echo "Running tests (optional)..."
      # - npm test # Uncomment if you have tests to run
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*' # Include all files in the deployment package